### PR TITLE
Use shield.io badges in README

### PR DESCRIPTION
**Pull request by valscion**
They're prettier and consistent among each other.

Also:

> Pixel-perfect   Retina-ready   Fast   Consistent   Hackable   No tracking

http://shields.io/

### CODE REVIEW

**Comment by valscion** [comment]
I wonder whether we'd like to actually use a smaller `maxAge` lifetime. What I initially put here was the default that came with the forms in shields.io

http://shields.io/#styles

**Comment by valscion** [comment]
Seems like the `maxAge` is just an optimization that was added to the examples and it broke a few things. I'll remove it — we can add it back if this repo becomes super popular in the future :smile:

**Comment by valscion** [comment]
Which ones are the best? I might even like the flat (which is the default, too) the best.

## flat-square

[Build Status](https://travis-ci.org/venuu/jsonapi-authorization) [Gem Version](https://rubygems.org/gems/jsonapi-authorization)

## flat

[Build Status](https://travis-ci.org/venuu/jsonapi-authorization) [Gem Version](https://rubygems.org/gems/jsonapi-authorization)

## plastic

[Build Status](https://travis-ci.org/venuu/jsonapi-authorization) [Gem Version](https://rubygems.org/gems/jsonapi-authorization)

**Comment by lime** [comment]
😆 I really don't have an opinion on this. Flat sounds fine by me.

**Comment by valscion** [comment]
I'll put flat and a cache for 1 hour. Those flashing badges are annoying and 1 hour old badges still are OK.

**Pull request merged**
