### PR TITLE
Resolution of relationships which employ the relation_name option

### PR DESCRIPTION
**Pull request by bsofiato**
This should resolve issue #35

### CODE REVIEW

**Comment by valscion** [comment]
Thank you! Do you mind fiddling around to add a test case for this somehow? I'm afraid we might break it in the future, if we don't have a test for it.

**Comment by bsofiatomatera** [comment]
Sure. I'll try to create a test case latter this day.

**Comment by bsofiato** [comment]
Sure. I'll try to create a test case latter today

**Comment by valscion** [comment]
Hiya @bsofiato! What's the status with this PR? Anything I can do to help you move forwards?

**Comment by bsofiato** [comment]
@valscion Just had a couple of more pressing issues and it kind slipped my mind. Gonna resume working on it.

**Comment by bsofiato** [comment]
@valscion Just commited the specs ;)

**Comment by valscion** [comment]
Thanks! :+1:

**Comment by valscion** [comment]
I just released version 0.8.2 with this fix. Thanks for your contribution!

**Pull request merged**
